import fetch from 'node-fetch'

let teams = [
    ['ari', 'arizona-cardinals'],
    ['bal/baltimore-ravens'],
    ['atl/atlanta-falcons'],
    ['buf/buffalo-bills'],
    ['car/carolina-panthers'],
    ['chi/chicago-bears'],
    ['cin/cincinnati-bengals'],
    ['cle/cleveland-browns'],
    ['dal/dallas-cowboys'],
    ['den/denver-broncos'],
    ['det/detroit-lions'],
    ['gb/green-bay-packers'],
    ['hou/houston-texans'],
    ['ind/indianapolis-colts'],
    ['jax/jacksonville-jaguars'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals'],
    ['ari', 'arizona-cardinals']
]
